In [1]:
import numpy as np
import pandas as pd

In [2]:
pip install tensorflow

  Using cached tensorflow-2.4.1-cp38-cp38-win_amd64.whl (370.7 MB)
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
  Using cached grpcio-1.32.0-cp38-cp38-win_amd64.whl (2.6 MB)
  Using cached protobuf-3.14.0-py2.py3-none-any.whl (173 kB)
Processing c:\users\hp\appdata\local\pip\cache\wheels\5f\fd\9e\b6cf5890494cb8ef0b5eaff72e5d55a70fb56316007d6dfe73\wrapt-1.12.1-py3-none-any.whl
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
  Using cached tensorboard-2.4.1-py3-none-any.whl (10.6 MB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 k

In [3]:
import tensorflow as tf

In [4]:
dataset = pd.read_csv(r"C:\Users\HP\Downloads\Churn_Modelling.csv")
X = dataset.iloc[:,3:-1].values
Y = dataset.iloc[:,-1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(Y)

[1 0 1 ... 1 1 0]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[: ,2] = le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
ann = tf.keras.models.Sequential()

In [18]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [21]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [23]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5896 - accuracy: 0.7612
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7880
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4382 - accuracy: 0.8000
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4420 - accuracy: 0.7907
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4216 - accuracy: 0.8046
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4177 - accuracy: 0.8036
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4136 - accuracy: 0.8217
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4125 - accuracy: 0.8214
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4130 - accuracy: 0.8166
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4174 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3241 - accuracy: 0.8701
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3316 - accuracy: 0.8668
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3373 - accuracy: 0.8622
Epoch 83/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3234 - accuracy: 0.8662
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3372 - accuracy: 0.8613
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3331 - accuracy: 0.8605
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3195 - accuracy: 0.8731
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3262 - accuracy: 0.8691
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3391 - accuracy: 0.8662
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3248 - accuracy: 

In [24]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [26]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1480  103]
 [ 212  205]]


0.8425